spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: TRACE
