###
POST {{host}}/api/menus
Content-Type: application/json

{
  "name": "후라이드+후라이드",
  "price": 19000,
  "menuGroupId": 1,
  "menuProductRequests": [{
    "productId": 1,
    "quantity": 10
  },
    {
      "productId": 2,
      "quantity": 10
    }]
}

###
GET {{host}}/api/menus

###
