### 메뉴를 등록한다 (메뉴 그룹 id, 메뉴 상품 정보로 상품 id와 양이 필요).
POST {{host}}/api/menus
Content-Type: application/json

{
  "name": "후라이드+후라이드",
  "price": 19000,
  "menuGroupId": 1,
  "menuProducts": [
    {
      "productId": 1,
      "quantity": 2
    }
  ]
}

### 메뉴의 목록을 조회한다.
GET {{host}}/api/menus

###
