###
POST {{host}}/api/kitchenpos.ui.order
Content-Type: kitchenpos.application/json

{
  "orderTableId": 1,
  "orderLineItems": [
    {
      "menuId": 1,
      "quantity": 1
    }
  ]
}

###
GET {{host}}/api/kitchenpos.ui.order

###
PUT {{host}}/api/kitchenpos.ui.order/1/kitchenpos.ui.order-status
Content-Type: kitchenpos.application/json

{
  "orderStatus": "MEAL"
}

###
PUT {{host}}/api/kitchenpos.ui.order/1/kitchenpos.ui.order-status
Content-Type: kitchenpos.application/json

{
  "orderStatus": "COMPLETION"
}

###
GET {{host}}/api/kitchenpos.ui.order/1
