### 테이블 추가
POST {{host}}/api/tables
Content-Type: application/json

{
  "numberOfGuests": 0,
  "empty": true
}

### 테이블 전체 조회
GET {{host}}/api/tables

### 테이블 상태 변경 - 사용
PUT {{host}}/api/tables/1/empty
Content-Type: application/json

{
  "empty": false
}

### 테이블 상태 변경 - 손님 수
PUT {{host}}/api/tables/1/number-of-guests
Content-Type: application/json

{
  "numberOfGuests": 4
}

### 테이블 상태 변경 - 사용하지 않음
PUT {{host}}/api/tables/1/empty
Content-Type: application/json

{
  "empty": true
}

### 테이블 상태 변경 - 사용하지 않음
PUT {{host}}/api/tables/2/empty
Content-Type: application/json

{
  "empty": true
}

###
