###
POST {{host}}/kitchenpos.api/table-groups
Content-Type: kitchenpos.menu.application/json

{
  "orderTables": [
    {
      "id": 1
    },
    {
      "id": 2
    }
  ]
}

###
DELETE {{host}}/kitchenpos.api/table-groups/1

###
