### 테이블 그룹 추가
POST {{host}}/api/table-groups
Content-Type: application/json

{
  "tables": [
    {
      "id": 1
    },
    {
      "id": 2
    }
  ]
}

### 테이블 그룹 제거
DELETE {{host}}/api/table-groups/1

###
