###
POST {{host}}/api/tables
Content-Type: application/json

{
  "numberOfGuests": 0,
  "orderable": true
}

###
GET {{host}}/api/tables

###
PUT {{host}}/api/tables/1/orderable
Content-Type: application/json

{
  "orderable": false
}

###
PUT {{host}}/api/tables/1/number-of-guests
Content-Type: application/json

{
  "numberOfGuests": 4
}

###
PUT {{host}}/api/tables/1/orderable
Content-Type: application/json

{
  "orderable": true
}

###
PUT {{host}}/api/tables/2/orderable
Content-Type: application/json

{
  "orderable": false
}

###
