###
POST {{host}}/kitchenpos.api/tables
Content-Type: kitchenpos.menu.application/json

{
  "numberOfGuests": 0,
  "empty": true
}

###
GET {{host}}/kitchenpos.api/tables

###
PUT {{host}}/kitchenpos.api/tables/1/empty
Content-Type: kitchenpos.menu.application/json

{
  "empty": false
}

###
PUT {{host}}/kitchenpos.api/tables/1/number-of-guests
Content-Type: kitchenpos.menu.application/json

{
  "numberOfGuests": 4
}

###
PUT {{host}}/kitchenpos.api/tables/1/empty
Content-Type: kitchenpos.menu.application/json

{
  "empty": true
}

###
PUT {{host}}/kitchenpos.api/tables/2/empty
Content-Type: kitchenpos.menu.application/json

{
  "empty": true
}

###
