set FOREIGN_KEY_CHECKS = 0;

TRUNCATE TABLE product;
TRUNCATE TABLE table_group;
TRUNCATE TABLE order_table;
TRUNCATE TABLE menu_product;
TRUNCATE TABLE menu_group;
TRUNCATE TABLE menu;
TRUNCATE TABLE order_line_item;
TRUNCATE TABLE orders;
