ALTER TABLE ORDER_LINE_ITEM
    DROP menu_id;

ALTER TABLE ORDER_LINE_ITEM
    ADD COLUMN price DECIMAL(19, 2) DEFAULT NULL;
ALTER TABLE ORDER_LINE_ITEM
    ADD COLUMN `name` VARCHAR(255) DEFAULT NULL;
