SET REFERENTIAL_INTEGRITY FALSE;

TRUNCATE TABLE MENU restart identity;
TRUNCATE TABLE MENU_GROUP restart identity;
TRUNCATE TABLE MENU_PRODUCT restart identity;
TRUNCATE TABLE ORDER_LINE_ITEM restart identity;
TRUNCATE TABLE ORDERS restart identity;
TRUNCATE TABLE ORDER_TABLE restart identity;
TRUNCATE TABLE PRODUCT restart identity;
TRUNCATE TABLE TABLE_GROUP restart identity;

SET REFERENTIAL_INTEGRITY TRUE;
