spring:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:kitchenpos-local;MODE=MYSQL;DB_CLOSE_DELAY=-1
    username: sa
    password:
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
