create table menu (
   menu_id bigint generated by default as identity,
    name varchar(255),
    price decimal(19,2),
    menu_group_id bigint,
    primary key (menu_id)
);

create table menu_group (
   menu_group_id bigint generated by default as identity,
    name varchar(255),
    primary key (menu_group_id)
);

create table menu_product (
   menu_product_id bigint generated by default as identity,
    product_id bigint,
    quantity bigint not null,
    menu_id bigint,
    primary key (menu_product_id)
);

create table order_line_item (
   order_line_item_id bigint generated by default as identity,
    quantity bigint not null,
    menu_id bigint,
    order_id bigint,
    primary key (order_line_item_id)
);

create table orders (
   order_id bigint generated by default as identity,
    order_status varchar(255),
    ordered_time timestamp,
    order_table_id bigint,
    primary key (order_id)
);

create table order_table (
   order_table_id bigint generated by default as identity,
    empty boolean not null,
    number_of_guests integer not null,
    table_group_id bigint,
    primary key (order_table_id)
);

create table product (
   product_id bigint generated by default as identity,
    name varchar(255),
    price decimal(19,2),
    primary key (product_id)
);

create table table_group (
   table_group_id bigint generated by default as identity,
    created_date timestamp,
    primary key (table_group_id)
);

alter table menu
   add constraint FK_MENU_MENU_GROUP
   foreign key (menu_group_id)
   references menu_group;

alter table menu_product
   add constraint FK_MENU_PRODUCT_MENU
   foreign key (menu_id)
   references menu;

alter table order_line_item
   add constraint FK_ORDER_LINE_ITEM_MENU
   foreign key (menu_id)
   references menu;

alter table order_line_item
   add constraint FK_ORDER_LINE_ITEM_ORDER
   foreign key (order_id)
   references orders;

alter table orders
   add constraint FK_ORDER_ORDER_TABLE
   foreign key (order_table_id)
   references order_table;

alter table order_table
   add constraint FK_ORDER_TABLE_TABLE_GROUP
   foreign key (table_group_id)
   references table_group;
