CREATE TABLE MENU
(
    ID            BIGINT         NOT NULL AUTO_INCREMENT,
    NAME          VARCHAR(255)   NOT NULL,
    PRICE         DECIMAL(19, 2) NOT NULL,
    MENU_GROUP_ID BIGINT         NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE MENU_GROUP
(
    ID   BIGINT       NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE MENU_PRODUCT
(
    SEQ        BIGINT NOT NULL AUTO_INCREMENT,
    QUANTITY   BIGINT NOT NULL,
    MENU_ID    BIGINT NOT NULL,
    PRODUCT_ID BIGINT NOT NULL,
    PRIMARY KEY (SEQ)
);

CREATE TABLE ORDER_LINE_ITEM
(
    SEQ      BIGINT NOT NULL AUTO_INCREMENT,
    QUANTITY BIGINT NOT NULL,
    MENU_ID  BIGINT NOT NULL,
    ORDER_ID BIGINT NOT NULL,
    PRIMARY KEY (SEQ)
);

CREATE TABLE ORDERS
(
    ID             BIGINT       NOT NULL AUTO_INCREMENT,
    ORDER_STATUS   VARCHAR(255) NOT NULL,
    ORDERED_TIME   DATETIME     NOT NULL,
    ORDER_TABLE_ID BIGINT       NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE ORDER_TABLE
(
    ID               BIGINT  NOT NULL AUTO_INCREMENT,
    EMPTY            BIT     NOT NULL,
    NUMBER_OF_GUESTS INTEGER NOT NULL,
    TABLE_GROUP_ID   BIGINT,
    PRIMARY KEY (ID)
);

CREATE TABLE PRODUCT
(
    ID    BIGINT         NOT NULL AUTO_INCREMENT,
    NAME  VARCHAR(255)   NOT NULL,
    PRICE DECIMAL(19, 2) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE TABLE_GROUP
(
    ID           BIGINT   NOT NULL AUTO_INCREMENT,
    CREATED_DATE DATETIME NOT NULL,
    PRIMARY KEY (ID)
);

ALTER TABLE MENU
    ADD CONSTRAINT FK_MENU_TO_MENU_GROUP
        FOREIGN KEY (MENU_GROUP_ID)
            REFERENCES MENU_GROUP (ID);

ALTER TABLE MENU_PRODUCT
    ADD CONSTRAINT FK_MENU_PRODUCT_TO_MENU
        FOREIGN KEY (MENU_ID)
            REFERENCES MENU (ID);

ALTER TABLE MENU_PRODUCT
    ADD CONSTRAINT FK_MENU_PRODUCT_TO_PRODUCT
        FOREIGN KEY (PRODUCT_ID)
            REFERENCES PRODUCT (ID);

ALTER TABLE ORDER_LINE_ITEM
    ADD CONSTRAINT FK_ORDER_LINE_ITEM_TO_MENU
        FOREIGN KEY (MENU_ID)
            REFERENCES MENU (ID);

ALTER TABLE ORDER_LINE_ITEM
    ADD CONSTRAINT FK_ORDER_LINE_ITEM_TO_ORDERS
        FOREIGN KEY (ORDER_ID)
            REFERENCES ORDERS (ID);

ALTER TABLE ORDERS
    ADD CONSTRAINT FK_ORDERS_TO_ORDER_TABLE
        FOREIGN KEY (ORDER_TABLE_ID)
            REFERENCES ORDER_TABLE (ID);

ALTER TABLE ORDER_TABLE
    ADD CONSTRAINT FK_ORDER_TABLE_TO_TABLE_GROUP
        FOREIGN KEY (TABLE_GROUP_ID)
            REFERENCES TABLE_GROUP (ID);
