create table menu_snapshot
(
    id              bigint         not null auto_increment,
    menu_id         bigint         not null,
    name            varchar(255)   not null,
    menu_group_name varchar(255)   not null,
    price           decimal(19, 2) not null,
    menu_updated_at timestamp,
    primary key (id)
);

create table menu_product_snapshot
(
    id               bigint generated by default as identity,
    name             varchar(255),
    price            numeric(19, 2),
    quantity         bigint,
    menu_snapshot_id bigint not null,
    primary key (id)
);

alter table menu_product_snapshot
    add constraint fk_menu_product_snapshot_to_menu_snapshot
        foreign key (menu_snapshot_id)
            references menu_snapshot (id);


alter table menu
    add column updated_at timestamp;

update menu
set updated_at = CURRENT_TIMESTAMP;

alter table menu
alter
column updated_at timestamp not null;


alter table order_line_item
    add column menu_snapshot_id bigint;

alter table order_line_item
    add constraint fk_order_line_item_to_menu_snapshot_id
        foreign key (menu_snapshot_id)
            references menu_snapshot (id);
