CREATE TABLE MENU_HISTORY
(
    ID                      BIGINT         NOT NULL AUTO_INCREMENT,
    NAME                    VARCHAR(255)   NOT NULL,
    PRICE                   DECIMAL(19, 2) NOT NULL,
    MENU_PRODUCT_HISTORY_ID BIGINT         NOT NULL
);

CREATE TABLE MENU_PRODUCT_HISTORY
(
    ID       BIGINT         NOT NULL AUTO_INCREMENT,
    NAME     VARCHAR(255)   NOT NULL,
    PRICE    DECIMAL(19, 2) NOT NULL,
    QUANTITY BIGINT         NOT NULL
);

ALTER TABLE MENU_HISTORY
    ADD CONSTRAINT FK_MENU_HISTORY_TO_MENU_PRODUCT_HISTORY
        FOREIGN KEY (MENU_PRODUCT_HISTORY_ID)
            REFERENCES MENU_PRODUCT_HISTORY (ID);
